### ISSUE TITLE
Clonable TypedMap

### ISSUE THREAD

**Issue by damooo** [kodieg/typedmap#7]
It would be useful, if there is a variant of TypedMap, that is clonable with values constrained to `Clone`.

**Comment by kodieg** [comment]
Yes, I can see that useful. I need to think how this can be achieved. Simplest idea would be to have `ClonableTypedMapValue` and `ClonableTypedMap`. Though, I would need to duplicate a lot of code.

**Comment by kodieg** [comment]
@damooo  It took quite a while but I figured out the way that constraining values might work. Prepared changes in 
https://github.com/kodieg/typedmap/pull/9

This change allows to specify "bounds" for both keys and values. For example, one may require that both key and values are Clone (and can be represented as some kind of DynClone trait):
```rust
let mut map: TypedMap::<(), CloneBounds, CloneBounds, _> = TypedMap::new_with_bounds();
```

An example of using Clone bounds can be found here:
https://github.com/kodieg/typedmap/blob/745528100000d51939c3d10a003226e02fe03100/src/clone.rs

Would that be something that could work for you?

**Comment by damooo** [comment]
Indeed, that works great.

**Comment by kodieg** [comment]
Just released those changes as v0.4. Additionally one can easily add own bound types (not only for Clone, but for own traits as well).

**Comment by iddm** [comment]
How do I store such a `TypedMap` inside a struct that derives `Clone`?

**Comment by kodieg** [comment]
Sorry for the delay. I implemented Clone for TypedMap with CloneBounds/SyncCloneBounds in v0.5.0 if you need really to clone the whole hashmap.  Otherwise you may want to just wrap everything with Arc<RwLock<...>>.
